# Generated by Django 2.1.5 on 2019-01-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_auto_20190105_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
