# Generated by Django 2.1.5 on 2019-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20190105_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
