# Generated by Django 2.1.5 on 2019-01-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20190105_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='date published'),
        ),
    ]
