# Generated by Django 2.1.5 on 2019-01-05 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_auto_20190105_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='id',
        ),
        migrations.AddField(
            model_name='idea',
            name='auto_inc_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
