# Generated by Django 2.1.5 on 2019-01-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_auto_20190105_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idea',
            name='pub_date',
            field=models.DateField(blank=True, null=True, unique=True, verbose_name='인스타 발행일'),
        ),
        migrations.AlterField(
            model_name='idea',
            name='subject',
            field=models.CharField(max_length=200, verbose_name='주제'),
        ),
    ]
