# Generated by Django 2.1.5 on 2019-01-17 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_auto_20190113_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayYami',
            fields=[
                ('picked_at', models.DateField(auto_now_add=True, primary_key=True, serialize=False)),
                ('yami', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Idea')),
            ],
        ),
    ]
